---
- hosts: all
  gather_facts: false
#  ignore_errors: true 
  tasks:
      -  name: Check the date
         command: datepaulg
         ignore_errors: yes 
      -  name: Check uptime 
         command: | 
            uptime
            date
            nproc


